# Generated by Django 5.0.7 on 2024-08-21 02:57

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdef12345', length=5, max_length=10, prefix='', unique=True)),
                ('titulo', models.CharField(default='Titulo', max_length=50)),
                ('paragrafo', models.TextField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapp.autor')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.DeleteModel(
            name='Noticia_p',
        ),
        migrations.DeleteModel(
            name='Paragrafo',
        ),
        migrations.DeleteModel(
            name='Titulo',
        ),
    ]
